# Development env for the projects.
## @see: https://github.com/wodby/docker4drupal

version: "2.4"

services:
  mariadb:
    image: wodby/mariadb:10.4-3.7.6
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD

  php:
    image: brainsum/damopen-php:8.1-dev-4.42.11
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DRUPAL_DATABASE_HOST: $DB_HOST
      DRUPAL_DATABASE_PORT: $DB_PORT
      DRUPAL_DATABASE_USERNAME: $DB_USER
      DRUPAL_DATABASE_PASSWORD: $DB_PASSWORD
      DRUPAL_DATABASE_NAME: $DB_NAME
      DRUPAL_DATABASE_DRIVER: $DB_DRIVER
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
      WODBY_ENVIRONMENT_NAME: $PROJECT_NAME
      DRUPAL_BASE_URI: "${PROJECT_BASE_URL}:8000"
      DRUPAL_HASH_SALT: "${DRUPAL_HASH_SALT}"
      ## Custom
      PHP_POST_MAX_SIZE: "500M"
      PHP_UPLOAD_MAX_FILESIZE: "500M"
      ##
    ## Read instructions at https://wodby.com/docs/stacks/php/local/#xdebug
    #      PHP_XDEBUG: 1
    #      PHP_XDEBUG_DEFAULT_ENABLE: 1
    #      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
    #      PHP_IDE_CONFIG: serverName=my-ide
    #      PHP_XDEBUG_IDEKEY: "my-ide"
    #      PHP_XDEBUG_REMOTE_HOST: host.docker.internal # Docker 18.03+ Mac/Win
    #      PHP_XDEBUG_REMOTE_HOST: 172.17.0.1 # Linux
    #      PHP_XDEBUG_REMOTE_HOST: 10.254.254.254 # macOS, Docker < 18.03
    #      PHP_XDEBUG_REMOTE_HOST: 10.0.75.1 # Windows, Docker < 18.03
    #      PHP_XDEBUG_REMOTE_LOG: /tmp/php-xdebug.log
    ## PHPUnit Drupal testing configurations
    #      SIMPLETEST_BASE_URL: "http://nginx"
    #      SIMPLETEST_DB: "mysql://drupal:drupal@mariadb/drupal#tests_"
    #      MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","goog:chromeOptions":{"args":["--disable-gpu","--headless"]}}, "http://chrome:9515"]'

    volumes:
      - ./:/var/www/html

  nginx:
    image: wodby/nginx:1.25-5.33.5
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: drupal10
      ## Custom
      NGINX_CLIENT_MAX_BODY_SIZE: "500m"
    volumes:
      - ./:/var/www/html
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)"

  mailhog:
    image: mailhog/mailhog
    labels:
      - "traefik.http.services.${PROJECT_NAME}_mailhog.loadbalancer.server.port=8025"
      - "traefik.http.routers.${PROJECT_NAME}_mailhog.rule=Host(`mailhog.${PROJECT_BASE_URL}`)"

  solr:
    image: wodby/solr:8-4.6.1
    environment:
      SOLR_DEFAULT_CONFIG_SET: "search_api_solr_4.0"
      SOLR_HEAP: 1024m
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_solr.rule=Host(`solr.${PROJECT_BASE_URL}`)"
