# Development env for the projects.
## @see: https://github.com/wodby/docker4drupal

version: "2.4"

services:
  traefik:
    image: traefik:v2.2.1
    command: --api.insecure=true --providers.docker
    ports:
      - '8000:80'
      #- '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
